#!/usr/bin/env python3
"""Regenerate the .rodata tables of stage3.s (same tables as build_tables()
in stage3.c): onext[3][1024] (u16), lnext[3][256] (u8), pdb (4-bit, packed).

Usage: python tools/gen_stage3_tables.py [stage3.s]      rewrite the tables in stage3.s
       python tools/gen_stage3_tables.py --c ref/tables.h  emit the same tables as C
"""
import sys
from collections import deque

CUBIES, ORIENTS, LOCS = 7, 729, 210
SOURCE = [[1, 4, 2, 0, 3, 5, 6], [0, 1, 2, 4, 5, 6, 3], [0, 2, 5, 3, 1, 4, 6]]
TWIST = [[1, 2, 0, 2, 1, 0, 0], [0, 0, 0, 1, 2, 1, 2], [0] * 7]


def quarter_turn(p, o, f):
    return ([p[SOURCE[f][i]] for i in range(CUBIES)],
            [(o[SOURCE[f][i]] + TWIST[f][i]) % 3 for i in range(CUBIES)])


def rank_orient(o):
    r = 0
    for i in range(6):
        r = r * 3 + o[i]
    return r


def loc_index(loc):
    r1 = loc[1] - (loc[1] > loc[0])
    r2 = loc[2] - (loc[2] > loc[0]) - (loc[2] > loc[1])
    return (loc[0] * 6 + r1) * 5 + r2


def decode_abstract(oi, l):
    o = [0] * 7
    s = 0
    for i in range(5, -1, -1):
        o[i] = oi % 3
        s += o[i]
        oi //= 3
    o[6] = (3 - s % 3) % 3
    l0, r1, r2 = l // 30, (l // 5) % 6, l % 5
    l1 = r1 + (r1 >= l0)
    a, b = min(l0, l1), max(l0, l1)
    l2 = r2 + (r2 >= a)
    l2 += l2 >= b
    p = [7] * 7
    p[l0], p[l1], p[l2] = 0, 1, 2
    k = 3
    for j in range(7):
        if p[j] == 7:
            p[j] = k
            k += 1
    return p, o


def build():
    onext = [[0] * 1024 for _ in range(3)]
    lnext = [[0] * 256 for _ in range(3)]
    for oi in range(ORIENTS):
        p, o = decode_abstract(oi, 0)
        for f in range(3):
            onext[f][oi] = rank_orient(quarter_turn(p, o, f)[1])
    for l in range(LOCS):
        p, o = decode_abstract(0, l)
        for f in range(3):
            np_, _ = quarter_turn(p, o, f)
            loc = [0] * 3
            for j in range(CUBIES):
                if np_[j] < 3:
                    loc[np_[j]] = j
            lnext[f][l] = loc_index(loc)
    n = ORIENTS * LOCS
    dist = [255] * n
    dist[0] = 0
    q = deque([0])
    while q:
        cur = q.popleft()
        oi, l = divmod(cur, LOCS)
        for f in range(3):
            no, nl = oi, l
            for _ in range(3):
                no, nl = onext[f][no], lnext[f][nl]
                ni = no * LOCS + nl
                if dist[ni] == 255:
                    dist[ni] = dist[cur] + 1
                    q.append(ni)
    assert 255 not in dist and max(dist) == 9
    pdb = bytearray((n + 1) // 2)
    for i, d in enumerate(dist):
        pdb[i >> 1] |= d << ((i & 1) * 4)
    return onext, lnext, bytes(pdb)


def emit(onext, lnext, pdb):
    out = ["        .align  2", "onext:                                  "
           "# u16 3 x 1024, row = face << 10"]
    for f in range(3):
        for i in range(0, 1024, 16):
            out.append("        .half   " + ", ".join(map(str, onext[f][i:i + 16])))
    out.append("lnext:                                  # u8 3 x 256, "
               "row = face << 8")
    for f in range(3):
        for i in range(0, 256, 32):
            out.append("        .byte   " + ", ".join(map(str, lnext[f][i:i + 32])))
    out.append("pdb:                                    # 153090 x 4 bit, "
               "low nibble = even index")
    for i in range(0, len(pdb), 32):
        out.append("        .byte   " + ", ".join(map(str, pdb[i:i + 32])))
    return "\n".join(out) + "\n"


def emit_c(onext, lnext, pdb):
    out = ["/* generated by tools/gen_stage3_tables.py --c, do not edit */",
           "static const uint16_t onext[3][1024] = {"]
    for f in range(3):
        out.append("    {" + ",".join(map(str, onext[f])) + "},")
    out.append("};")
    out.append("static const uint8_t lnext[3][256] = {")
    for f in range(3):
        out.append("    {" + ",".join(map(str, lnext[f])) + "},")
    out.append("};")
    out.append("static const uint8_t pdb[%d] = {" % len(pdb))
    for i in range(0, len(pdb), 32):
        out.append("    " + ",".join(map(str, pdb[i:i + 32])) + ",")
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) > 2 and sys.argv[1] == "--c":
        open(sys.argv[2], "w", newline="\n").write(emit_c(*build()))
        return
    path = sys.argv[1] if len(sys.argv) > 1 else "stage3.s"
    src = open(path, encoding="utf-8").read()
    b = "# BEGIN GENERATED TABLES tools/gen_stage3_tables.py\n"
    e = "# END GENERATED TABLES"
    i, j = src.index(b) + len(b), src.index(e)
    onext, lnext, pdb = build()
    open(path, "w", encoding="utf-8", newline="\n").write(
        src[:i] + emit(onext, lnext, pdb) + src[j:])
    print("tables: onext %d B, lnext %d B, pdb %d B" % (6144, 768, len(pdb)))


if __name__ == "__main__":
    main()
